FROM confluentinc/cp-kafka-connect:6.1.1

RUN confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:10.0.2
#RUN confluent-hub install --no-prompt confluentinc/kafka-connect-elasticsearch:11.0.4

#TODO install io.apicurio:apicurio-registry-utils-serde:2.0.0.Final

# Then run `jdbc_connector_source.sh`
